name: tost-gpu
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>1.24
  - h5py
  - mpi4py
  - mpich
  - pymeep=*=mpi_mpich_*
  - matplotlib
  - scipy
  - meshio
  - pip
  - pip:
      - -e ".[gpu]"
